dist: trusty

sudo: required

language: php

php: 7.2

services: mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart
  - sudo mysql -e "create database homestead charset=utf8mb4 collate=utf8mb4_unicode_ci"
  - sudo mysql -e "create user homestead@localhost identified by 'secret'"
  - sudo mysql -e "grant all on homestead.* to homestead@localhost"

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - cp .env.example .env
  - php artisan key:generate
  
script: php artisan migrate

cache:
  directories:
  - $HOME/.composer/cache
