language: php

php: 7.2

services: mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty
sudo: required

before_install:
  - mysql -e "create database homestead charset=utf8mb4 collate=utf8mb4_unicode_ci"
  - mysql -e "create user homestead@localhost identified by 'secret'"
  - mysql -e "grant all on homestead.* to homestead@localhost"

install: travis_retry composer install --no-interaction --prefer-source

before_script:
  - cp .env.example .env
  - php artisan key:generate
  
script: php artisan migrate

cache:
  directories:
  - $HOME/.composer/cache
